# Generated by Django 3.1.5 on 2021-01-29 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviewee', '0004_auto_20210110_1850'),
        ('interviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('token', models.CharField(default='hey', max_length=32)),
                ('question', models.TextField()),
                ('interviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviewee.interviewee')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviewer.interviewer')),
            ],
        ),
    ]
