# Generated by Django 3.1.5 on 2021-02-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewroom',
            name='freeze',
            field=models.BooleanField(default=False),
        ),
    ]
