# Generated by Django 3.1.5 on 2021-01-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyadmin',
            name='id',
        ),
        migrations.AlterField(
            model_name='companyadmin',
            name='username',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
