# Generated by Django 3.1.5 on 2021-01-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20210108_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyadmin',
            name='email',
            field=models.EmailField(max_length=500),
        ),
        migrations.AlterField(
            model_name='companyadmin',
            name='password',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='companyadmin',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
