# Generated by Django 3.1.5 on 2021-01-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_auto_20210109_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyadmin',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='companyadmin',
            name='status',
        ),
        migrations.AddField(
            model_name='companyadmin',
            name='username',
            field=models.CharField(default=1, max_length=250, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyadmin',
            name='email',
            field=models.EmailField(max_length=500),
        ),
    ]
