# Generated by Django 3.1.5 on 2021-01-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_auto_20210109_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyadmin',
            name='username',
        ),
        migrations.AddField(
            model_name='companyadmin',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyadmin',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companyadmin',
            name='email',
            field=models.EmailField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
