# Generated by Django 3.1.5 on 2021-01-09 15:52

import Login.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_auto_20210109_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(default=Login.models.ten_minutes_hence)),
                ('admin_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.companyadmin')),
            ],
        ),
    ]
