# Generated by Django 3.1.5 on 2021-01-11 16:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0013_auto_20210111_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passwordrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='xyz', max_length=200)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 1, 11, 16, 34, 18, 990015, tzinfo=utc))),
                ('admin_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.companyadmin')),
            ],
        ),
        migrations.AlterField(
            model_name='verification',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 11, 16, 34, 18, 990015, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='preset_request',
        ),
    ]
