# Generated by Django 3.1.5 on 2021-01-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewee',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interviewee',
            name='phone',
            field=models.CharField(default='xxxxxxxxxxx', max_length=13),
        ),
        migrations.AlterField(
            model_name='interviewee',
            name='resume_link',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
