# Generated by Django 3.1.5 on 2021-01-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewee', '0003_auto_20210110_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewee',
            name='phone',
            field=models.CharField(default='', max_length=13),
        ),
    ]
